sudo: required
dist: trusty
language: node_js
node_js:
- "7"
before_script:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: script
  script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add ./dist
  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
  on:
    branch: master
