sudo: required
dist: trusty
language: node_js
node_js:
- "7"
before_script:
- npm install
script:
- npm run lint
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x $TRAVIS_BUILD_DIR/deploy.sh && $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
